name: Deploy to GCP VM on push

on:
  push:
    branches:
      - devops

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run Tests
      run: npm run test

    - name: Build the project
      run: npm run build

    - name: Setup SSH key for GCP VM
      run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.GCP_VM_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to GCP VM
      run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_VM_USERNAME }}@${{ secrets.GCP_VM_IP }} << 'EOF'
            cd /var/www/SeerHive
            git pull origin devops
            npm install
            npm run build
            pm2 restart ${{ secrets.GCP_VM_APP_NAME }}
          EOF
