name: Deploy to GCP VM on push

on:
  push:
    branches:
      - devops

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Build the project
        run: npm run build

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.GCP_VM_IP }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.GCP_VM_USERNAME }}@${{ secrets.GCP_VM_IP }} \
          "mkdir -p /home/${{ secrets.GCP_VM_USERNAME }}/seerHive-Devops"
    
          rsync -avz -e "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no" \
          --exclude='node_modules' \
          --exclude='.git' \
          .next/ \
          public/ \
          package.json \
          ${{ secrets.GCP_VM_USERNAME }}@${{ secrets.GCP_VM_IP }}:/home/${{ secrets.GCP_VM_USERNAME }}/seerHive-Devops/

