name: React App Deployment

on:
  push:
    branches: [ "devops" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Test the application
      run: npm run test

    - name: Build application
      run: |
        npm run build
        ls -la .next/

    # Authenticate with GCP using Service Account JSON
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: turing-agent-462018-i5

    - name: Copy files to GCP VM using gcloud
      run: |
        gcloud compute scp --recurse .next "${{ secrets.GCP_VM_USERNAME }}@${{ secrets.GCP_VM_INSTANCE_NAME }}:/var/www/SeerHive" \
        --zone=${{ secrets.GCP_VM_ZONE }} \
        --quiet
      env:
        CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: ${{ steps.auth.outputs.credentials_file_path }}




    - name: SSH and deploy using gcloud
      run: |
        gcloud compute ssh ${{ secrets.GCP_VM_USERNAME }}@${{ secrets.GCP_VM_NAME }} \
          --zone=${{ secrets.GCP_VM_ZONE }} \
          --command="cd /var/www/SeerHive && npm install && \
            (pm2 list | grep -q seerHive && pm2 restart seerHive --update-env || pm2 start npm --name 'seerHive' -- start) && pm2 save"
