name: React App Deployment

on:
  push:
    branches: [ "devops" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install

    - name: Test the application
      run: npm run test
    
    - name: Build application
      run: |
        npm run build
        ls -la .next/

    - name: Deploy to GCP VM
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ "34.0.4.159" }}
        username: ${{ "seertksys" }}
        key: ${{ "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBCCvqp0DNtQpYVLHW/rVMdKKNbLN3O0yriPG6W2dLouOWSbsKrat961K6Bja+gf/HMCs9brV8F+g3whAT+Wj9a0= google-ssh {"userName":"seertksys@gmail.com","expireOn":"2025-06-13T22:01:48+0000"}" }}
        source: ".next/*"
        target: "/var/www/SeerHive"
        rm: true
        overwrite: true

    - name: Install dependencies and manage PM2 process
      uses: appleboy/ssh-action@v1
      with:
         host: ${{ "34.0.4.159" }}
         username: ${{ "seertksys" }}
         key: ${{ "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBCCvqp0DNtQpYVLHW/rVMdKKNbLN3O0yriPG6W2dLouOWSbsKrat961K6Bja+gf/HMCs9brV8F+g3whAT+Wj9a0= google-ssh {"userName":"seertksys@gmail.com","expireOn":"2025-06-13T22:01:48+0000"}" }}
         script: |
           cd /var/www/SeerHive
           npm install
           if pm2 list | grep -q seerHive; then
           echo "Restarting existing seerHive process..."
           pm2 restart seerHive --update-env
           else
           echo "Starting new seerHive process..."
           pm2 start npm --name "seerHive" -- start
           fi
           pm2 save
