name: React App Deployment

on:
  push:
    branches: [ "devops" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install

    - name: Test the application
      run: npm run test
    
    - name: Build application
      run: |
        npm run build
        ls -la .next/

    - name: Authenticate with Google Cloud
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      run: |
        echo "$GCP_SA_KEY" > key.json
        gcloud auth activate-service-account --key-file=key.json
        gcloud config set project turing-agent-462018-i5
        rm -f key.json

    - name: Install gcloud CLI (if needed)
      run: |
        if ! command -v gcloud &> /dev/null; then
          echo "Installing gcloud CLI..."
          sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates gnupg
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update && sudo apt-get install -y google-cloud-sdk
        fi

    - name: Deploy files to GCP VM
      run: |
        gcloud compute scp --recurse .next/* ${{ secrets.GCP_VM_USERNAME }}@${{ secrets.GCP_VM_IP }}:/var/www/SeerHive \
          --zone=asia-south2-a  # Replace with your VM's zone

    - name: Restart application on VM
      run: |
        gcloud compute ssh ${{ secrets.GCP_VM_USERNAME }}@${{ secrets.GCP_VM_IP }} \
          --zone=asia-south2-a \  # Replace with your VM's zone
          --command="cd /var/www/SeerHive && npm install && if pm2 list | grep -q seerHive; then pm2 restart seerHive --update-env; else pm2 start npm --name \"seerHive\" -- start; fi && pm2 save"
